# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI (solution)

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '20 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: solution
    - name: Cache Setup
      uses: actions/cache@v2
      with:
        path: |
          ~/cache
          ~/.dts/
          !~/cache/exclude
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      
    - name: Use (Volta) Node.js ${{ matrix.node-version }}
      uses: volta-cli/action@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn
    - name: Build
      run: yarn build
    - name: Build Docs
      run: yarn api-report && yarn api-docs
    - name: Run tests
      run: yarn test
